name: Clean Workflows

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  clean_workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      DRY: false
    steps:
      - name: delete workflow runs - all ( > 14 days )
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 14
          dry: ${{ env.DRY }}
      - name: delete workflow runs - status ( > 5 days )
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_conclusions: |
            action_required
            cancelled
            failure
            neutral
            skipped
            stale
            timed_out
          save_period: 5
          save_min_runs_number: 0
          dry: ${{ env.DRY }}
