name: Nightly Build

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: andronics/base

jobs:
  
  build-and-release:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: container registry login
        uses: docker/login-action@b4bedf8053341df3b5a9f9e0f2cf4e79e27360c6
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: metadata extraction
        id: meta
        uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD' tz='Europe/London'}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: commit count
        run: echo "COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_ENV"
      
      - name: build and push
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        if: ${{ env.COMMIT_COUNT > 0 }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: clean
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json